### PR TITLE
Export types from package.json

### PR DESCRIPTION
**Pull request by asquithea**
Fixes https://github.com/microsoft/TypeScript/issues/52363

### CODE REVIEW

**Comment by JohnnyRacer** [comment]
@samhirtarif 

Hello, is it possible for this pull request to be merged? It's not possible to import any of the components when using TypeScript and `.tsx` files without errors as it complains about the types.

**Comment by airtonix** [comment]
please senpai...

notice us

**Review by mrsafalpiya — APPROVED** [review]

**Review by fede1132 — APPROVED** [review]
LGTM

**Review by samhirtarif — APPROVED** [review]

**Comment by samhirtarif** [comment]
@asquithea thanks for this!

And sorry for the wait guys! This will be published shortly!

**Pull request merged**
